language: cpp
services:
  - docker

os: linux
arch:
  - amd64

jobs:
  include:
    - name: "Database Server"
      env: REPO_SLUG=ravenx8/osirose REPO_TAG=database-latest
      script:
        - docker build -t $REPO_SLUG:$REPO_TAG - < ${TRAVIS_BUILD_DIR}/osirose-server/database.Dockerfile
    - name: "Node Server"
      env: REPO_SLUG=ravenx8/osirose REPO_TAG=node-latest
      script:
        - docker build -t $REPO_SLUG:$REPO_TAG - < ${TRAVIS_BUILD_DIR}/osirose-server/node.Dockerfile
    - name: "Login Server"
      env: REPO_SLUG=ravenx8/osirose REPO_TAG=login-latest
      script:
        - docker build -t $REPO_SLUG:$REPO_TAG - < ${TRAVIS_BUILD_DIR}/osirose-server/login.Dockerfile
    - name: "Char Server"
      env: REPO_SLUG=ravenx8/osirose REPO_TAG=char-latest
      script:
        - docker build -t $REPO_SLUG:$REPO_TAG - < ${TRAVIS_BUILD_DIR}/osirose-server/char.Dockerfile
    - name: "Map Server"
      env: REPO_SLUG=ravenx8/osirose REPO_TAG=map-latest
      script:
        - docker build -t $REPO_SLUG:$REPO_TAG - < ${TRAVIS_BUILD_DIR}/osirose-server/map.Dockerfile

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
